### ISSUE TITLE
Cannot  connect to testnet node as of 06/30/2016

### ISSUE THREAD

**Issue by arbedout** [bitcoin-hivemind/testnet-canonical#1]
root@debian:~$ /usr/src/hivemind/src/hivemind-cli addnode 162.243.37.30 onetry
error: couldn't connect to server

I've tried the hivemind QT client as well and  it just stays at '8 weeks behind' without syncing. Is the testnet seed node offline?

**Comment by CryptAxe** [comment]
I've just checked and hivemindd is running properly on the server. I'll see if I can sync, also just to confirm do you have testnet=1 in your config file?

**Comment by CryptAxe** [comment]
Okay I just synced up a new node, I didn't have any connection issues so I'm going to bet that you are connecting to the main network instead of the testnet. Let me know if it's still giving you trouble though and we can figure it out :)

**Comment by arbedout** [comment]
Here is my configuration:

root@debian:~$ cat .hivemind/hivemind.conf 
rpcuser=hivemindrpc
rpcpassword=_redacted_
testnet=1

and a screenshot of the qt client - it seems I can in fact connect to the node but I still see that i'm 8 weeks behind, is the latest block 279 as the client says?

_photo deleted_

**Comment by CryptAxe** [comment]
Okay, everything is actually working then! I don't know if you've seen the https://github.com/bitcoin-hivemind/testnet-canonical testnet repository but we actually stop the testnet node from syncing beyond 280 blocks so that developers can get a clean environment if they erase their local chain and resync. You can mine your own blocks very easily (no difficulty), and then you will not get the out of sync message anymore.
